language: python

python:
    - 3.5

sudo: false

env:
    - TOX_ENV=py27-dj18
    - TOX_ENV=py32-dj18
    - TOX_ENV=py33-dj18
    - TOX_ENV=py34-dj18
    - TOX_ENV=py27-dj19
    - TOX_ENV=py34-dj19
    - TOX_ENV=py35-dj19

matrix:
  fast_finish: true

install:
  - pip install virtualenv tox coveralls

script:
  - tox -e $TOX_ENV

after_success:
  - coveralls
